language: c

matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh

install:
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/bin/activate root
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - conda install -q pip conda-build anaconda-client

script:
  - conda build -c chogan/label/dev -c conda-forge recipe

after_success:
  - chmod +x ./conda_upload.sh

deploy:
  - provider: script
    script: ./conda_upload.sh main
    on:
      tags: true
    skip_cleanup: true

  - provider: script
    script: ./conda_upload.sh dev
    on:
      branch: dev
    skip_cleanup: true
